name: Generate files
on:
  push:
    branches-ignore:
      - 'gh-pages'
jobs:
  generate-files:
    runs-on: ubuntu-latest
    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "The workflow is now ready to test your code on the runner."
      - name: Generate the files in docker
        run: mkdir -p scripts/dist
      - run: ls scripts/dist/ -lh
      - name: Deploy to gh-pages
        shell: bash -l {0}
        run: |
          set -x
          set -e
          cd scripts/dist/
          git init
          git checkout -b gh-pages
          git remote add origin git@github.com:OSGeo/spatialreference.org.git

          git config user.email "proj.bot@proj.bot"
          git config user.name "PROJ deploybot"

          touch .nojekyll
          echo "spatialreference.org" > CNAME

          git add -A
          git commit -m "update with results of commit ${{ github.sha }}"
          git push -f origin gh-pages